- name: start_apache2
  service:
    name: apache2
    state: started

- name: reload_apache2
  service:
    name: apache2
    state: reloaded

- name: restart_apache2
  service:
    name: apache2
    state: restarted
