
- name: copy_authorized_keys
  when: ssh_installed is success
  file:
    path: /home/viktor/.ssh
    state: directory
    owner: viktor
    group: viktor
    mode: 0664
  notify:
    - reload_ssh_server
