- name: install_fail2ban
  apt:
    pkg: fail2ban
    state: present
    update_cache: true
  register: fail2ban_installed

- name: copy_fail2ban_jail_config
  when: fail2ban_installed is success
  copy:
    src: jail.conf
    dest: /etc/fail2ban/jail.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart_fail2ban
